name: Test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"
      - name: Restore project
        run: dotnet restore
      - name: Test
        run: dotnet test fsharp-game.slnx --verbosity normal
